FROM golang:1.12.1

LABEL maintainer="Masato Yamazaki <mas9612@gmail.com>"

RUN go get -u github.com/mas9612/wrapups

RUN go get -t -d -v ./...
WORKDIR /go/src/github.com/mas9612/wrapups

CMD ["go", "test", "-v", "./..."]
